import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Caparica Bike Rental | Costa da Caparica</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Caparica Bike Rental!
        </h1>
          <div className='container'>

          </div>
          <Image src="/home_slide.jpg" width={1920} height={672}/>
        
          <p className={styles.description}>
          Comming Soon!</p>

         
      </main>

      <footer className={styles.footer}>
        <p>
         
          Powered by{' Caparica Bike Rental'}
          <span className={styles.logo}>
          
          </span>
        </p>
      </footer>
    </div>
  )
}
